apiVersion: apps/v1
kind: Deployment
metadata:
  name: glass
  labels:
    exivity.k8s/component: glass
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: glass
      {{- include "exivity.default_labels" . | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: glass
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      containers:
      - name: glass
        image: {{ .Values.images.glass }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
        ports:
        - containerPort: 443
      imagePullSecrets:
      - name: ghcr
---
apiVersion: v1
kind: Service
metadata:
  name: glass
  labels:
    exivity.k8s/component: glass
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    exivity.k8s/component: glass
    {{- include "exivity.default_labels" . | indent 4 }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
