{{if not .Values.rabbitMQ.useExternalServers}}
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    exivity.k8s/component: rabbitMQ
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5672
  clusterIP: None
  selector:
    exivity.k8s/component: rabbitMQ
    {{- include "exivity.default_labels" . | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exivity-rabbit
  labels:
    exivity.k8s/component: rabbitMQ
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: rabbitMQ
      {{- include "exivity.default_labels" . | indent 6 }}
  serviceName: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: rabbitMQ
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      containers:
      - name: exivity-rabbit
        image: rabbitmq:latest
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitMQ.user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitMQ.password }}
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.rabbitMQ.vhost }}
{{end}}
