apiVersion: v1
kind: Secret
metadata:
  name: exivity-app-key
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
stringData:
  {{- if .Release.IsInstall }}
  app_key: {{ randAlphaNum 32 | b64enc }}
  {{ else }}
  app_key: {{ index (lookup "v1" "Secret" .Release.Namespace "exivity-app-key").data "app_key" }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: exivity-jwt-secret
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
stringData:
  {{- if .Release.IsInstall }}
  jwt_secret: {{ randAlphaNum 32 | b64enc }}
  {{ else }}
  jwt_secret: {{ index (lookup "v1" "Secret" .Release.Namespace "exivity-jwt-secret").data "jwt_secret" }}
  {{ end }}
---
{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: exivity-license
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
stringData:
  license_key: {{ .Values.license }}
{{ end }}
