apiVersion: v1
kind: Secret
metadata:
  name: exivity-app-key
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
stringData:
  app_key: {{ required "A valid exivity app key needs to be provided" .Values.appKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: exivity-jwt-secret
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
stringData:
  jwt_secret: {{ required "A valid jwt secret for proximity" .Values.JWTSecret }}
---
{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: exivity-license
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
stringData:
  license_key: {{ .Values.license }}
{{ end }}
