apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-etl-config
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  {{- if .Values.singleNode }}
  - ReadWriteOnce
  {{- else }}
  - ReadWriteMany
  {{- end }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-exported
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  {{- if .Values.singleNode }}
  - ReadWriteOnce
  {{- else }}
  - ReadWriteMany
  {{- end }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-extracted
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  {{- if .Values.singleNode }}
  - ReadWriteOnce
  {{- else }}
  - ReadWriteMany
  {{- end }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-import
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  {{- if .Values.singleNode }}
  - ReadWriteOnce
  {{- else }}
  - ReadWriteMany
  {{- end }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-report
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  {{- if .Values.singleNode }}
  - ReadWriteOnce
  {{- else }}
  - ReadWriteMany
  {{- end }}
  resources:
    requests:
      storage: 1Gi
