ingress:
  enable: true
  host: localhost

storage:
  singleNode: true
  helmResourcePolicyKeep: false

# bitnami/postgresql chart config
postgresql:
  image:
    tag: 12.10.0
    pullPolicy: Always
  auth:
    database: exivity
    username: exivity
    password: Password12!
    postgresPassword: Password13!
  fullnameOverride: exivity-postgres

database:
  initialise: true

rabbitmq:
  user: guest
  password: guest
  vhost: /
  host: rabbit
  port: 5672
  useExternalServers: false

service:
  chronos:
    image: ghcr.io/exivity/chronos
  dbInit:
    image: ghcr.io/exivity/db
  edify:
    image: ghcr.io/exivity/edify
  glass:
    image: ghcr.io/exivity/glass
  griffon:
    image: ghcr.io/exivity/griffon
  horizon:
    image: ghcr.io/exivity/horizon
  pigeon:
    image: ghcr.io/exivity/pigeon
    tag: k8s
  proximityApi:
    image: docker.io/exivity/proximity-api
  proximityCli:
    image: ghcr.io/exivity/proximity-cli
  rabbitmq:
    image: rabbitmq
    tag: 3.9
  transcript:
    image: ghcr.io/exivity/transcript
  use:
    image: ghcr.io/exivity/use
