# Private values that need to be configured
# license:
# appKey:
# JWTSecret:

imagePullSecret: regcred
namespace: exivity
host: localhost
singleNode: true
deployment-name: exivity

# Database config
database:
  username: postgres
  password: Password12!
  dbname: exivity
  host: db # only change when you have set useExternalDatabase to true
  port: 5432 # only change when you have set useExternalDatabase to true
  useExternalDatabase: false
  initialise: true

# RabbitMQ config
rabbitMQ:
  user: guest
  password: guest
  vhost: /
  host: rabbit
  port: 5672
  useExternalServers: false

images:
  chronos: ghcr.io/exivity/chronos:k8s
  db_init: ghcr.io/exivity/db:k8s
  edify: ghcr.io/exivity/edify:k8s
  glass: ghcr.io/exivity/glass:develop
  griffon: ghcr.io/exivity/griffon:k8s
  horizon: ghcr.io/exivity/horizon:k8s
  pigeon: ghcr.io/exivity/pigeon:k8s
  proximity_api: ghcr.io/exivity/proximity-api:k8s
  proximity_cli: ghcr.io/exivity/proximity-cli:k8s
  transcript: ghcr.io/exivity/transcript:k8s
  use: ghcr.io/exivity/use:k8s
