name: Release Images

on:
  create:
  workflow_dispatch:

jobs:
  if: ${{ startsWith(github.ref, 'refs/tags/') }}
  image-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
        - proximity-api
    steps:
    - name: release images with tags
      uses: exivity/actions/docker-retag-image@chore/build-script-retag-action
      with:
        oldTag: develop
        newTag: ${{ github.ref_name }}
        name: ${{ matrix.name }}
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
