name: Release Images

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  image-release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
        - chronos
        - db
        - edify
        - glass
        - griffon
        - horizon
        - proximity-api
        - proximity-cli
        - transcript
        - use
    steps:
    - name: release images with tags
      uses: exivity/actions/docker-retag-image@chore/build-script-retag-action
      with:
        oldTag: develop
        newTag: ${{ github.ref_name }}
        name: ${{ matrix.name }}
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
